### ISSUE TITLE
Server: If /manifest circleId not available still return a circle

### ISSUE THREAD

**Issue by exrhizo** [coordinape/coordinape-backend#69]
Currently, the FE will request a circle from the manifest that is stored in local storage.

@levity  requested that we have a per account storage of selected circle

I think it is better to stay in the existing circle.

Either way, although odd, can we have the `/manifest` route return the first available circle, if the requested one is not available?

**Comment by levity** [comment]
> @levity requested that we have a per account storage of selected circle
> I think it is better to stay in the existing circle.

I don't see these things as in conflict...

We need per-account storage of the selected circle, because there's no guarantee that two accounts will both be in the same circle. But if they are, sure, use the existing one.

**Comment by levity** [comment]
> Either way, although odd, can we have the /manifest route return the first available circle, if the requested one is not available?

Is there a different way to do this? I imagine a workflow like:

- switch account
- find valid circles for that account
- pick the existing one, if it's valid
- otherwise pick the first valid circle

anyway, i see that /manifest already uses the first valid circle if no circle ID is passed in--it just doesn't handle it correctly if you pass in an invalid one... which you shouldn't be doing anyway?
